services:
    Plugin\SearchQueryLogger\SearchQueryLogger:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
        tags:
            - { name: 'kernel.event_subscriber' }
